dataset: mini-imagenet
dataset_args: {split: test}

#load: ./save/MODEL_FOLDER/EPOCH_X.pth
load: ./save/meta_mini-imagenet-1shot_meta-baseline-resnet12/max-va.pth

# Replace load with load_encoder for loading the encoder only (e.g. for testing Classifier-Baseline)
