#train_dataset: mini-imagenet
train_dataset: train_ck+
train_dataset_args: {split: train, augment: resize}
val_dataset: test_ck+
val_dataset_args: {split: train_phase_val}
fs_dataset: test_casme2
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet18
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 7}
#load_encoder: ./save/classifier_mini-imagenet_resnet12/epoch-last.pth
load_encoder: ./save/im800-resnet18.pth

batch_size: 128
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.01, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 5
visualize_datasets: true
